//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Stephen\source\repos\BASICLanguageParser\BASICLanguageParser.Grammar\ColorBasic.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BASICLanguageParser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ColorBasicParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IColorBasicListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] ColorBasicParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] ColorBasicParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] ColorBasicParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] ColorBasicParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ColorBasicParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ColorBasicParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ColorBasicParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ColorBasicParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.characterExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacterExpression([NotNull] ColorBasicParser.CharacterExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.characterExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacterExpression([NotNull] ColorBasicParser.CharacterExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] ColorBasicParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] ColorBasicParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.relop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelop([NotNull] ColorBasicParser.RelopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.relop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelop([NotNull] ColorBasicParser.RelopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.variableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableList([NotNull] ColorBasicParser.VariableListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.variableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableList([NotNull] ColorBasicParser.VariableListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.absfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsfunc([NotNull] ColorBasicParser.AbsfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.absfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsfunc([NotNull] ColorBasicParser.AbsfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ascfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAscfunc([NotNull] ColorBasicParser.AscfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ascfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAscfunc([NotNull] ColorBasicParser.AscfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.sgnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSgnfunc([NotNull] ColorBasicParser.SgnfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.sgnfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSgnfunc([NotNull] ColorBasicParser.SgnfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.intfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntfunc([NotNull] ColorBasicParser.IntfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.intfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntfunc([NotNull] ColorBasicParser.IntfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.sinfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSinfunc([NotNull] ColorBasicParser.SinfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.sinfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSinfunc([NotNull] ColorBasicParser.SinfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.rndfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRndfunc([NotNull] ColorBasicParser.RndfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.rndfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRndfunc([NotNull] ColorBasicParser.RndfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.lenfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLenfunc([NotNull] ColorBasicParser.LenfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.lenfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLenfunc([NotNull] ColorBasicParser.LenfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.valfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValfunc([NotNull] ColorBasicParser.ValfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.valfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValfunc([NotNull] ColorBasicParser.ValfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.chrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChrfunc([NotNull] ColorBasicParser.ChrfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.chrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChrfunc([NotNull] ColorBasicParser.ChrfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.midfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMidfunc([NotNull] ColorBasicParser.MidfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.midfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMidfunc([NotNull] ColorBasicParser.MidfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.leftfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeftfunc([NotNull] ColorBasicParser.LeftfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.leftfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeftfunc([NotNull] ColorBasicParser.LeftfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.rightfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRightfunc([NotNull] ColorBasicParser.RightfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.rightfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRightfunc([NotNull] ColorBasicParser.RightfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.strfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrfunc([NotNull] ColorBasicParser.StrfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.strfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrfunc([NotNull] ColorBasicParser.StrfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.inkeyfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInkeyfunc([NotNull] ColorBasicParser.InkeyfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.inkeyfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInkeyfunc([NotNull] ColorBasicParser.InkeyfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.joystkfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoystkfunc([NotNull] ColorBasicParser.JoystkfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.joystkfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoystkfunc([NotNull] ColorBasicParser.JoystkfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.eoffunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEoffunc([NotNull] ColorBasicParser.EoffuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.eoffunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEoffunc([NotNull] ColorBasicParser.EoffuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.peekfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPeekfunc([NotNull] ColorBasicParser.PeekfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.peekfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPeekfunc([NotNull] ColorBasicParser.PeekfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.pointfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointfunc([NotNull] ColorBasicParser.PointfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.pointfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointfunc([NotNull] ColorBasicParser.PointfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.memfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemfunc([NotNull] ColorBasicParser.MemfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.memfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemfunc([NotNull] ColorBasicParser.MemfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.usrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsrfunc([NotNull] ColorBasicParser.UsrfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.usrfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsrfunc([NotNull] ColorBasicParser.UsrfuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.letstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetstmt([NotNull] ColorBasicParser.LetstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.letstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetstmt([NotNull] ColorBasicParser.LetstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.dimstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimstmt([NotNull] ColorBasicParser.DimstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.dimstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimstmt([NotNull] ColorBasicParser.DimstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.forstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForstmt([NotNull] ColorBasicParser.ForstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.forstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForstmt([NotNull] ColorBasicParser.ForstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.nextstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNextstmt([NotNull] ColorBasicParser.NextstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.nextstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNextstmt([NotNull] ColorBasicParser.NextstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifthenelsestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfthenelsestmt([NotNull] ColorBasicParser.IfthenelsestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifthenelsestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfthenelsestmt([NotNull] ColorBasicParser.IfthenelsestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifthenelsenumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfthenelsenumstmt([NotNull] ColorBasicParser.IfthenelsenumstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifthenelsenumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfthenelsenumstmt([NotNull] ColorBasicParser.IfthenelsenumstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifthenstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfthenstmt([NotNull] ColorBasicParser.IfthenstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifthenstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfthenstmt([NotNull] ColorBasicParser.IfthenstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifnumelsenumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfnumelsenumstmt([NotNull] ColorBasicParser.IfnumelsenumstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifnumelsenumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfnumelsenumstmt([NotNull] ColorBasicParser.IfnumelsenumstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfnumstmt([NotNull] ColorBasicParser.IfnumstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfnumstmt([NotNull] ColorBasicParser.IfnumstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstmt([NotNull] ColorBasicParser.IfstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstmt([NotNull] ColorBasicParser.IfstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.gotonumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotonumstmt([NotNull] ColorBasicParser.GotonumstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.gotonumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotonumstmt([NotNull] ColorBasicParser.GotonumstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.gotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotostmt([NotNull] ColorBasicParser.GotostmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.gotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotostmt([NotNull] ColorBasicParser.GotostmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.gosubnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGosubnumstmt([NotNull] ColorBasicParser.GosubnumstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.gosubnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGosubnumstmt([NotNull] ColorBasicParser.GosubnumstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.gosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGosubstmt([NotNull] ColorBasicParser.GosubstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.gosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGosubstmt([NotNull] ColorBasicParser.GosubstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ongotonumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOngotonumstmt([NotNull] ColorBasicParser.OngotonumstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ongotonumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOngotonumstmt([NotNull] ColorBasicParser.OngotonumstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ongotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOngotostmt([NotNull] ColorBasicParser.OngotostmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ongotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOngotostmt([NotNull] ColorBasicParser.OngotostmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ongosubnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOngosubnumstmt([NotNull] ColorBasicParser.OngosubnumstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ongosubnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOngosubnumstmt([NotNull] ColorBasicParser.OngosubnumstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ongosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOngosubstmt([NotNull] ColorBasicParser.OngosubstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ongosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOngosubstmt([NotNull] ColorBasicParser.OngosubstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.returnstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnstmt([NotNull] ColorBasicParser.ReturnstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.returnstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnstmt([NotNull] ColorBasicParser.ReturnstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.readstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadstmt([NotNull] ColorBasicParser.ReadstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.readstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadstmt([NotNull] ColorBasicParser.ReadstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.restorestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRestorestmt([NotNull] ColorBasicParser.RestorestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.restorestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRestorestmt([NotNull] ColorBasicParser.RestorestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.newstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewstmt([NotNull] ColorBasicParser.NewstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.newstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewstmt([NotNull] ColorBasicParser.NewstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.endstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndstmt([NotNull] ColorBasicParser.EndstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.endstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndstmt([NotNull] ColorBasicParser.EndstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.stopstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStopstmt([NotNull] ColorBasicParser.StopstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.stopstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStopstmt([NotNull] ColorBasicParser.StopstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.runstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRunstmt([NotNull] ColorBasicParser.RunstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.runstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRunstmt([NotNull] ColorBasicParser.RunstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.clearstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClearstmt([NotNull] ColorBasicParser.ClearstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.clearstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClearstmt([NotNull] ColorBasicParser.ClearstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.contstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContstmt([NotNull] ColorBasicParser.ContstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.contstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContstmt([NotNull] ColorBasicParser.ContstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.liststmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListstmt([NotNull] ColorBasicParser.ListstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.liststmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListstmt([NotNull] ColorBasicParser.ListstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.lliststmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLliststmt([NotNull] ColorBasicParser.LliststmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.lliststmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLliststmt([NotNull] ColorBasicParser.LliststmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.inputstmt1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputstmt1([NotNull] ColorBasicParser.Inputstmt1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.inputstmt1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputstmt1([NotNull] ColorBasicParser.Inputstmt1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.printstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintstmt([NotNull] ColorBasicParser.PrintstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.printstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintstmt([NotNull] ColorBasicParser.PrintstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.printtabstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrinttabstmt([NotNull] ColorBasicParser.PrinttabstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.printtabstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrinttabstmt([NotNull] ColorBasicParser.PrinttabstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.printhashstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrinthashstmt([NotNull] ColorBasicParser.PrinthashstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.printhashstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrinthashstmt([NotNull] ColorBasicParser.PrinthashstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.printatstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintatstmt([NotNull] ColorBasicParser.PrintatstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.printatstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintatstmt([NotNull] ColorBasicParser.PrintatstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.setstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetstmt([NotNull] ColorBasicParser.SetstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.setstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetstmt([NotNull] ColorBasicParser.SetstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.resetstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResetstmt([NotNull] ColorBasicParser.ResetstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.resetstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResetstmt([NotNull] ColorBasicParser.ResetstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.clsstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClsstmt([NotNull] ColorBasicParser.ClsstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.clsstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClsstmt([NotNull] ColorBasicParser.ClsstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.execstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExecstmt([NotNull] ColorBasicParser.ExecstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.execstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExecstmt([NotNull] ColorBasicParser.ExecstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.pokestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPokestmt([NotNull] ColorBasicParser.PokestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.pokestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPokestmt([NotNull] ColorBasicParser.PokestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.motorstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMotorstmt([NotNull] ColorBasicParser.MotorstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.motorstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMotorstmt([NotNull] ColorBasicParser.MotorstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.audiostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAudiostmt([NotNull] ColorBasicParser.AudiostmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.audiostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAudiostmt([NotNull] ColorBasicParser.AudiostmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.soundstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoundstmt([NotNull] ColorBasicParser.SoundstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.soundstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoundstmt([NotNull] ColorBasicParser.SoundstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.cloadstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCloadstmt([NotNull] ColorBasicParser.CloadstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.cloadstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCloadstmt([NotNull] ColorBasicParser.CloadstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.cloadmstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCloadmstmt([NotNull] ColorBasicParser.CloadmstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.cloadmstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCloadmstmt([NotNull] ColorBasicParser.CloadmstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.csavestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCsavestmt([NotNull] ColorBasicParser.CsavestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.csavestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCsavestmt([NotNull] ColorBasicParser.CsavestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.csavemstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCsavemstmt([NotNull] ColorBasicParser.CsavemstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.csavemstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCsavemstmt([NotNull] ColorBasicParser.CsavemstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.skipfstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkipfstmt([NotNull] ColorBasicParser.SkipfstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.skipfstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkipfstmt([NotNull] ColorBasicParser.SkipfstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.openstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenstmt([NotNull] ColorBasicParser.OpenstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.openstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenstmt([NotNull] ColorBasicParser.OpenstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.closestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClosestmt([NotNull] ColorBasicParser.ClosestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.closestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClosestmt([NotNull] ColorBasicParser.ClosestmtContext context);
}
} // namespace BASICLanguageParser
