//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Stephen\source\repos\BASICLanguageParser\BASICLanguageParser.Grammar\ColorBasic.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BASICLanguageParser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IColorBasicListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ColorBasicBaseListener : IColorBasicListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] ColorBasicParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] ColorBasicParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] ColorBasicParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] ColorBasicParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ColorBasicParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ColorBasicParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] ColorBasicParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] ColorBasicParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.characterExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharacterExpression([NotNull] ColorBasicParser.CharacterExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.characterExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharacterExpression([NotNull] ColorBasicParser.CharacterExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] ColorBasicParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] ColorBasicParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.relationalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalOperator([NotNull] ColorBasicParser.RelationalOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.relationalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalOperator([NotNull] ColorBasicParser.RelationalOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.logicalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOperator([NotNull] ColorBasicParser.LogicalOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.logicalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOperator([NotNull] ColorBasicParser.LogicalOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.variableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableList([NotNull] ColorBasicParser.VariableListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.variableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableList([NotNull] ColorBasicParser.VariableListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.absfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbsfunc([NotNull] ColorBasicParser.AbsfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.absfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbsfunc([NotNull] ColorBasicParser.AbsfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ascfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAscfunc([NotNull] ColorBasicParser.AscfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ascfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAscfunc([NotNull] ColorBasicParser.AscfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.sgnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSgnfunc([NotNull] ColorBasicParser.SgnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.sgnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSgnfunc([NotNull] ColorBasicParser.SgnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.intfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntfunc([NotNull] ColorBasicParser.IntfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.intfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntfunc([NotNull] ColorBasicParser.IntfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.sinfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSinfunc([NotNull] ColorBasicParser.SinfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.sinfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSinfunc([NotNull] ColorBasicParser.SinfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.rndfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRndfunc([NotNull] ColorBasicParser.RndfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.rndfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRndfunc([NotNull] ColorBasicParser.RndfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.lenfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLenfunc([NotNull] ColorBasicParser.LenfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.lenfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLenfunc([NotNull] ColorBasicParser.LenfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.valfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValfunc([NotNull] ColorBasicParser.ValfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.valfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValfunc([NotNull] ColorBasicParser.ValfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.chrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChrfunc([NotNull] ColorBasicParser.ChrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.chrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChrfunc([NotNull] ColorBasicParser.ChrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.midfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMidfunc([NotNull] ColorBasicParser.MidfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.midfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMidfunc([NotNull] ColorBasicParser.MidfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.leftfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeftfunc([NotNull] ColorBasicParser.LeftfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.leftfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeftfunc([NotNull] ColorBasicParser.LeftfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.rightfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRightfunc([NotNull] ColorBasicParser.RightfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.rightfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRightfunc([NotNull] ColorBasicParser.RightfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.strfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrfunc([NotNull] ColorBasicParser.StrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.strfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrfunc([NotNull] ColorBasicParser.StrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.inkeyfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInkeyfunc([NotNull] ColorBasicParser.InkeyfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.inkeyfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInkeyfunc([NotNull] ColorBasicParser.InkeyfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.joystkfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoystkfunc([NotNull] ColorBasicParser.JoystkfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.joystkfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoystkfunc([NotNull] ColorBasicParser.JoystkfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.eoffunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEoffunc([NotNull] ColorBasicParser.EoffuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.eoffunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEoffunc([NotNull] ColorBasicParser.EoffuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.peekfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPeekfunc([NotNull] ColorBasicParser.PeekfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.peekfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPeekfunc([NotNull] ColorBasicParser.PeekfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.pointfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointfunc([NotNull] ColorBasicParser.PointfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.pointfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointfunc([NotNull] ColorBasicParser.PointfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.memfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemfunc([NotNull] ColorBasicParser.MemfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.memfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemfunc([NotNull] ColorBasicParser.MemfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.usrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsrfunc([NotNull] ColorBasicParser.UsrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.usrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsrfunc([NotNull] ColorBasicParser.UsrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.letstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetstmt([NotNull] ColorBasicParser.LetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.letstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetstmt([NotNull] ColorBasicParser.LetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.dimstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimstmt([NotNull] ColorBasicParser.DimstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.dimstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimstmt([NotNull] ColorBasicParser.DimstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.forstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstmt([NotNull] ColorBasicParser.ForstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.forstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstmt([NotNull] ColorBasicParser.ForstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.nextstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNextstmt([NotNull] ColorBasicParser.NextstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.nextstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNextstmt([NotNull] ColorBasicParser.NextstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifthenelsestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfthenelsestmt([NotNull] ColorBasicParser.IfthenelsestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifthenelsestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfthenelsestmt([NotNull] ColorBasicParser.IfthenelsestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifthenelsenumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfthenelsenumstmt([NotNull] ColorBasicParser.IfthenelsenumstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifthenelsenumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfthenelsenumstmt([NotNull] ColorBasicParser.IfthenelsenumstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifthenstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfthenstmt([NotNull] ColorBasicParser.IfthenstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifthenstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfthenstmt([NotNull] ColorBasicParser.IfthenstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifnumelsenumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfnumelsenumstmt([NotNull] ColorBasicParser.IfnumelsenumstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifnumelsenumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfnumelsenumstmt([NotNull] ColorBasicParser.IfnumelsenumstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifnumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfnumstmt([NotNull] ColorBasicParser.IfnumstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifnumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfnumstmt([NotNull] ColorBasicParser.IfnumstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] ColorBasicParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] ColorBasicParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.gotonumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotonumstmt([NotNull] ColorBasicParser.GotonumstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.gotonumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotonumstmt([NotNull] ColorBasicParser.GotonumstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.gotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotostmt([NotNull] ColorBasicParser.GotostmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.gotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotostmt([NotNull] ColorBasicParser.GotostmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.gosubnumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGosubnumstmt([NotNull] ColorBasicParser.GosubnumstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.gosubnumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGosubnumstmt([NotNull] ColorBasicParser.GosubnumstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.gosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGosubstmt([NotNull] ColorBasicParser.GosubstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.gosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGosubstmt([NotNull] ColorBasicParser.GosubstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ongotonumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngotonumstmt([NotNull] ColorBasicParser.OngotonumstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ongotonumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngotonumstmt([NotNull] ColorBasicParser.OngotonumstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ongotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngotostmt([NotNull] ColorBasicParser.OngotostmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ongotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngotostmt([NotNull] ColorBasicParser.OngotostmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ongosubnumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngosubnumstmt([NotNull] ColorBasicParser.OngosubnumstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ongosubnumstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngosubnumstmt([NotNull] ColorBasicParser.OngosubnumstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.ongosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngosubstmt([NotNull] ColorBasicParser.OngosubstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.ongosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngosubstmt([NotNull] ColorBasicParser.OngosubstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.returnstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnstmt([NotNull] ColorBasicParser.ReturnstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.returnstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnstmt([NotNull] ColorBasicParser.ReturnstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.readstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadstmt([NotNull] ColorBasicParser.ReadstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.readstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadstmt([NotNull] ColorBasicParser.ReadstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.restorestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRestorestmt([NotNull] ColorBasicParser.RestorestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.restorestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRestorestmt([NotNull] ColorBasicParser.RestorestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.newstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewstmt([NotNull] ColorBasicParser.NewstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.newstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewstmt([NotNull] ColorBasicParser.NewstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.endstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndstmt([NotNull] ColorBasicParser.EndstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.endstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndstmt([NotNull] ColorBasicParser.EndstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.stopstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStopstmt([NotNull] ColorBasicParser.StopstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.stopstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStopstmt([NotNull] ColorBasicParser.StopstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.runstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRunstmt([NotNull] ColorBasicParser.RunstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.runstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRunstmt([NotNull] ColorBasicParser.RunstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.clearstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClearstmt([NotNull] ColorBasicParser.ClearstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.clearstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClearstmt([NotNull] ColorBasicParser.ClearstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.contstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContstmt([NotNull] ColorBasicParser.ContstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.contstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContstmt([NotNull] ColorBasicParser.ContstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.liststmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListstmt([NotNull] ColorBasicParser.ListstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.liststmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListstmt([NotNull] ColorBasicParser.ListstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.lliststmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLliststmt([NotNull] ColorBasicParser.LliststmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.lliststmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLliststmt([NotNull] ColorBasicParser.LliststmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.inputstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputstmt1([NotNull] ColorBasicParser.Inputstmt1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.inputstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputstmt1([NotNull] ColorBasicParser.Inputstmt1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.printstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintstmt([NotNull] ColorBasicParser.PrintstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.printstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintstmt([NotNull] ColorBasicParser.PrintstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.printtabstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrinttabstmt([NotNull] ColorBasicParser.PrinttabstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.printtabstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrinttabstmt([NotNull] ColorBasicParser.PrinttabstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.printhashstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrinthashstmt([NotNull] ColorBasicParser.PrinthashstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.printhashstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrinthashstmt([NotNull] ColorBasicParser.PrinthashstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.printatstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintatstmt([NotNull] ColorBasicParser.PrintatstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.printatstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintatstmt([NotNull] ColorBasicParser.PrintatstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.setstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetstmt([NotNull] ColorBasicParser.SetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.setstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetstmt([NotNull] ColorBasicParser.SetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.resetstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResetstmt([NotNull] ColorBasicParser.ResetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.resetstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResetstmt([NotNull] ColorBasicParser.ResetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.clsstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClsstmt([NotNull] ColorBasicParser.ClsstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.clsstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClsstmt([NotNull] ColorBasicParser.ClsstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.execstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExecstmt([NotNull] ColorBasicParser.ExecstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.execstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExecstmt([NotNull] ColorBasicParser.ExecstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.pokestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPokestmt([NotNull] ColorBasicParser.PokestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.pokestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPokestmt([NotNull] ColorBasicParser.PokestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.motorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMotorstmt([NotNull] ColorBasicParser.MotorstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.motorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMotorstmt([NotNull] ColorBasicParser.MotorstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.audiostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAudiostmt([NotNull] ColorBasicParser.AudiostmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.audiostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAudiostmt([NotNull] ColorBasicParser.AudiostmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.soundstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSoundstmt([NotNull] ColorBasicParser.SoundstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.soundstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSoundstmt([NotNull] ColorBasicParser.SoundstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.cloadstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCloadstmt([NotNull] ColorBasicParser.CloadstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.cloadstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCloadstmt([NotNull] ColorBasicParser.CloadstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.cloadmstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCloadmstmt([NotNull] ColorBasicParser.CloadmstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.cloadmstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCloadmstmt([NotNull] ColorBasicParser.CloadmstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.csavestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCsavestmt([NotNull] ColorBasicParser.CsavestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.csavestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCsavestmt([NotNull] ColorBasicParser.CsavestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.csavemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCsavemstmt([NotNull] ColorBasicParser.CsavemstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.csavemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCsavemstmt([NotNull] ColorBasicParser.CsavemstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.skipfstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkipfstmt([NotNull] ColorBasicParser.SkipfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.skipfstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkipfstmt([NotNull] ColorBasicParser.SkipfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.openstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpenstmt([NotNull] ColorBasicParser.OpenstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.openstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpenstmt([NotNull] ColorBasicParser.OpenstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ColorBasicParser.closestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClosestmt([NotNull] ColorBasicParser.ClosestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ColorBasicParser.closestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClosestmt([NotNull] ColorBasicParser.ClosestmtContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace BASICLanguageParser
