//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Stephen\source\repos\ECB2_Lib\ECB2_Lib.Parser.Grammar\jvmBasic.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ECB2_Lib.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IjvmBasicListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class jvmBasicBaseListener : IjvmBasicListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] jvmBasicParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] jvmBasicParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] jvmBasicParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] jvmBasicParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.amperoper"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmperoper([NotNull] jvmBasicParser.AmperoperContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.amperoper"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmperoper([NotNull] jvmBasicParser.AmperoperContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.linenumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinenumber([NotNull] jvmBasicParser.LinenumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.linenumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinenumber([NotNull] jvmBasicParser.LinenumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.amprstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmprstmt([NotNull] jvmBasicParser.AmprstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.amprstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmprstmt([NotNull] jvmBasicParser.AmprstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] jvmBasicParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] jvmBasicParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.vardecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVardecl([NotNull] jvmBasicParser.VardeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.vardecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVardecl([NotNull] jvmBasicParser.VardeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.printstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintstmt1([NotNull] jvmBasicParser.Printstmt1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.printstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintstmt1([NotNull] jvmBasicParser.Printstmt1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.printlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintlist([NotNull] jvmBasicParser.PrintlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.printlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintlist([NotNull] jvmBasicParser.PrintlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.getstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetstmt([NotNull] jvmBasicParser.GetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.getstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetstmt([NotNull] jvmBasicParser.GetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.letstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetstmt([NotNull] jvmBasicParser.LetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.letstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetstmt([NotNull] jvmBasicParser.LetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.variableassignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableassignment([NotNull] jvmBasicParser.VariableassignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.variableassignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableassignment([NotNull] jvmBasicParser.VariableassignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.relop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelop([NotNull] jvmBasicParser.RelopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.relop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelop([NotNull] jvmBasicParser.RelopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.neq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNeq([NotNull] jvmBasicParser.NeqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.neq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNeq([NotNull] jvmBasicParser.NeqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] jvmBasicParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] jvmBasicParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.forstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstmt1([NotNull] jvmBasicParser.Forstmt1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.forstmt1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstmt1([NotNull] jvmBasicParser.Forstmt1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.forstmt2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstmt2([NotNull] jvmBasicParser.Forstmt2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.forstmt2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstmt2([NotNull] jvmBasicParser.Forstmt2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.nextstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNextstmt([NotNull] jvmBasicParser.NextstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.nextstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNextstmt([NotNull] jvmBasicParser.NextstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.inputstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputstmt([NotNull] jvmBasicParser.InputstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.inputstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputstmt([NotNull] jvmBasicParser.InputstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.readstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReadstmt([NotNull] jvmBasicParser.ReadstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.readstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReadstmt([NotNull] jvmBasicParser.ReadstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.dimstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimstmt([NotNull] jvmBasicParser.DimstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.dimstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimstmt([NotNull] jvmBasicParser.DimstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.gotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotostmt([NotNull] jvmBasicParser.GotostmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.gotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotostmt([NotNull] jvmBasicParser.GotostmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.gosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGosubstmt([NotNull] jvmBasicParser.GosubstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.gosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGosubstmt([NotNull] jvmBasicParser.GosubstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.pokestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPokestmt([NotNull] jvmBasicParser.PokestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.pokestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPokestmt([NotNull] jvmBasicParser.PokestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.callstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallstmt([NotNull] jvmBasicParser.CallstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.callstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallstmt([NotNull] jvmBasicParser.CallstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.hplotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHplotstmt([NotNull] jvmBasicParser.HplotstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.hplotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHplotstmt([NotNull] jvmBasicParser.HplotstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.vplotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVplotstmt([NotNull] jvmBasicParser.VplotstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.vplotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVplotstmt([NotNull] jvmBasicParser.VplotstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.plotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlotstmt([NotNull] jvmBasicParser.PlotstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.plotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlotstmt([NotNull] jvmBasicParser.PlotstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.ongotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngotostmt([NotNull] jvmBasicParser.OngotostmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.ongotostmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngotostmt([NotNull] jvmBasicParser.OngotostmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.ongosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOngosubstmt([NotNull] jvmBasicParser.OngosubstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.ongosubstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOngosubstmt([NotNull] jvmBasicParser.OngosubstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.vtabstmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVtabstmnt([NotNull] jvmBasicParser.VtabstmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.vtabstmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVtabstmnt([NotNull] jvmBasicParser.VtabstmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.htabstmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtabstmnt([NotNull] jvmBasicParser.HtabstmntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.htabstmnt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtabstmnt([NotNull] jvmBasicParser.HtabstmntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.himemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHimemstmt([NotNull] jvmBasicParser.HimemstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.himemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHimemstmt([NotNull] jvmBasicParser.HimemstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.lomemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLomemstmt([NotNull] jvmBasicParser.LomemstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.lomemstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLomemstmt([NotNull] jvmBasicParser.LomemstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.datastmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatastmt([NotNull] jvmBasicParser.DatastmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.datastmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatastmt([NotNull] jvmBasicParser.DatastmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.datum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatum([NotNull] jvmBasicParser.DatumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.datum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatum([NotNull] jvmBasicParser.DatumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.waitstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWaitstmt([NotNull] jvmBasicParser.WaitstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.waitstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWaitstmt([NotNull] jvmBasicParser.WaitstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.xdrawstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXdrawstmt([NotNull] jvmBasicParser.XdrawstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.xdrawstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXdrawstmt([NotNull] jvmBasicParser.XdrawstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.drawstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrawstmt([NotNull] jvmBasicParser.DrawstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.drawstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrawstmt([NotNull] jvmBasicParser.DrawstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.defstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefstmt([NotNull] jvmBasicParser.DefstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.defstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefstmt([NotNull] jvmBasicParser.DefstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.tabstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTabstmt([NotNull] jvmBasicParser.TabstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.tabstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTabstmt([NotNull] jvmBasicParser.TabstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.speedstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeedstmt([NotNull] jvmBasicParser.SpeedstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.speedstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeedstmt([NotNull] jvmBasicParser.SpeedstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.rotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotstmt([NotNull] jvmBasicParser.RotstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.rotstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotstmt([NotNull] jvmBasicParser.RotstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.scalestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalestmt([NotNull] jvmBasicParser.ScalestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.scalestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalestmt([NotNull] jvmBasicParser.ScalestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.colorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColorstmt([NotNull] jvmBasicParser.ColorstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.colorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColorstmt([NotNull] jvmBasicParser.ColorstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.hcolorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHcolorstmt([NotNull] jvmBasicParser.HcolorstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.hcolorstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHcolorstmt([NotNull] jvmBasicParser.HcolorstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.hlinstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHlinstmt([NotNull] jvmBasicParser.HlinstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.hlinstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHlinstmt([NotNull] jvmBasicParser.HlinstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.vlinstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVlinstmt([NotNull] jvmBasicParser.VlinstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.vlinstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVlinstmt([NotNull] jvmBasicParser.VlinstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.onerrstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnerrstmt([NotNull] jvmBasicParser.OnerrstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.onerrstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnerrstmt([NotNull] jvmBasicParser.OnerrstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.prstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrstmt([NotNull] jvmBasicParser.PrstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.prstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrstmt([NotNull] jvmBasicParser.PrstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.instmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstmt([NotNull] jvmBasicParser.InstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.instmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstmt([NotNull] jvmBasicParser.InstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.storestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStorestmt([NotNull] jvmBasicParser.StorestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.storestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStorestmt([NotNull] jvmBasicParser.StorestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.recallstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecallstmt([NotNull] jvmBasicParser.RecallstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.recallstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecallstmt([NotNull] jvmBasicParser.RecallstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.liststmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListstmt([NotNull] jvmBasicParser.ListstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.liststmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListstmt([NotNull] jvmBasicParser.ListstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.popstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPopstmt([NotNull] jvmBasicParser.PopstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.popstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPopstmt([NotNull] jvmBasicParser.PopstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.amptstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmptstmt([NotNull] jvmBasicParser.AmptstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.amptstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmptstmt([NotNull] jvmBasicParser.AmptstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.includestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludestmt([NotNull] jvmBasicParser.IncludestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.includestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludestmt([NotNull] jvmBasicParser.IncludestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.endstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndstmt([NotNull] jvmBasicParser.EndstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.endstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndstmt([NotNull] jvmBasicParser.EndstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.returnstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnstmt([NotNull] jvmBasicParser.ReturnstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.returnstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnstmt([NotNull] jvmBasicParser.ReturnstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.restorestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRestorestmt([NotNull] jvmBasicParser.RestorestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.restorestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRestorestmt([NotNull] jvmBasicParser.RestorestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] jvmBasicParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] jvmBasicParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.func_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_([NotNull] jvmBasicParser.Func_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.func_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_([NotNull] jvmBasicParser.Func_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.signExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignExpression([NotNull] jvmBasicParser.SignExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.signExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignExpression([NotNull] jvmBasicParser.SignExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.exponentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponentExpression([NotNull] jvmBasicParser.ExponentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.exponentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponentExpression([NotNull] jvmBasicParser.ExponentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.multiplyingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplyingExpression([NotNull] jvmBasicParser.MultiplyingExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.multiplyingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplyingExpression([NotNull] jvmBasicParser.MultiplyingExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.addingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddingExpression([NotNull] jvmBasicParser.AddingExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.addingExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddingExpression([NotNull] jvmBasicParser.AddingExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] jvmBasicParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] jvmBasicParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] jvmBasicParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] jvmBasicParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.var_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_([NotNull] jvmBasicParser.Var_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.var_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_([NotNull] jvmBasicParser.Var_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.varname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarname([NotNull] jvmBasicParser.VarnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.varname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarname([NotNull] jvmBasicParser.VarnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.varsuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarsuffix([NotNull] jvmBasicParser.VarsuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.varsuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarsuffix([NotNull] jvmBasicParser.VarsuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarlist([NotNull] jvmBasicParser.VarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarlist([NotNull] jvmBasicParser.VarlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.exprlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprlist([NotNull] jvmBasicParser.ExprlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.exprlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprlist([NotNull] jvmBasicParser.ExprlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.sqrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqrfunc([NotNull] jvmBasicParser.SqrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.sqrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqrfunc([NotNull] jvmBasicParser.SqrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.chrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChrfunc([NotNull] jvmBasicParser.ChrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.chrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChrfunc([NotNull] jvmBasicParser.ChrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.lenfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLenfunc([NotNull] jvmBasicParser.LenfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.lenfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLenfunc([NotNull] jvmBasicParser.LenfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.ascfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAscfunc([NotNull] jvmBasicParser.AscfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.ascfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAscfunc([NotNull] jvmBasicParser.AscfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.midfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMidfunc([NotNull] jvmBasicParser.MidfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.midfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMidfunc([NotNull] jvmBasicParser.MidfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.pdlfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPdlfunc([NotNull] jvmBasicParser.PdlfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.pdlfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPdlfunc([NotNull] jvmBasicParser.PdlfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.peekfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPeekfunc([NotNull] jvmBasicParser.PeekfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.peekfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPeekfunc([NotNull] jvmBasicParser.PeekfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.intfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntfunc([NotNull] jvmBasicParser.IntfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.intfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntfunc([NotNull] jvmBasicParser.IntfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.spcfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpcfunc([NotNull] jvmBasicParser.SpcfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.spcfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpcfunc([NotNull] jvmBasicParser.SpcfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.frefunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrefunc([NotNull] jvmBasicParser.FrefuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.frefunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrefunc([NotNull] jvmBasicParser.FrefuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.posfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosfunc([NotNull] jvmBasicParser.PosfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.posfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosfunc([NotNull] jvmBasicParser.PosfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.usrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsrfunc([NotNull] jvmBasicParser.UsrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.usrfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsrfunc([NotNull] jvmBasicParser.UsrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.leftfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeftfunc([NotNull] jvmBasicParser.LeftfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.leftfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeftfunc([NotNull] jvmBasicParser.LeftfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.rightfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRightfunc([NotNull] jvmBasicParser.RightfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.rightfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRightfunc([NotNull] jvmBasicParser.RightfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.strfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrfunc([NotNull] jvmBasicParser.StrfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.strfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrfunc([NotNull] jvmBasicParser.StrfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.fnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnfunc([NotNull] jvmBasicParser.FnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.fnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnfunc([NotNull] jvmBasicParser.FnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.valfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValfunc([NotNull] jvmBasicParser.ValfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.valfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValfunc([NotNull] jvmBasicParser.ValfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.scrnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScrnfunc([NotNull] jvmBasicParser.ScrnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.scrnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScrnfunc([NotNull] jvmBasicParser.ScrnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.sinfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSinfunc([NotNull] jvmBasicParser.SinfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.sinfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSinfunc([NotNull] jvmBasicParser.SinfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.cosfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCosfunc([NotNull] jvmBasicParser.CosfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.cosfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCosfunc([NotNull] jvmBasicParser.CosfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.tanfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTanfunc([NotNull] jvmBasicParser.TanfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.tanfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTanfunc([NotNull] jvmBasicParser.TanfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.atnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtnfunc([NotNull] jvmBasicParser.AtnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.atnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtnfunc([NotNull] jvmBasicParser.AtnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.rndfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRndfunc([NotNull] jvmBasicParser.RndfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.rndfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRndfunc([NotNull] jvmBasicParser.RndfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.sgnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSgnfunc([NotNull] jvmBasicParser.SgnfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.sgnfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSgnfunc([NotNull] jvmBasicParser.SgnfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.expfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpfunc([NotNull] jvmBasicParser.ExpfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.expfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpfunc([NotNull] jvmBasicParser.ExpfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.logfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogfunc([NotNull] jvmBasicParser.LogfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.logfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogfunc([NotNull] jvmBasicParser.LogfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.absfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbsfunc([NotNull] jvmBasicParser.AbsfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.absfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbsfunc([NotNull] jvmBasicParser.AbsfuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="jvmBasicParser.tabfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTabfunc([NotNull] jvmBasicParser.TabfuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="jvmBasicParser.tabfunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTabfunc([NotNull] jvmBasicParser.TabfuncContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ECB2_Lib.Parser
