//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Stephen\source\repos\BASICLanguageParser\BASICLanguageParser.Grammar\TestBasic.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BASICLanguageParser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class TestBasicLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, LET=2, COMMENT=3, REM=4, DIGIT_SEQUENCE=5, WS=6, EOL=7;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "LET", "COMMENT", "REM", "DIGIT_SEQUENCE", "WS", "EOL", "DIGIT"
	};


	public TestBasicLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public TestBasicLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "':'", "'LET'", null, null, null, null, "'\r\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "LET", "COMMENT", "REM", "DIGIT_SEQUENCE", "WS", "EOL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TestBasic.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TestBasicLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\t', '?', '\b', '\x1', '\x4', '\x2', '\t', '\x2', '\x4', 
		'\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', 
		'\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', 
		'\b', '\x4', '\t', '\t', '\t', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\a', '\x4', '\x1C', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x1F', '\v', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x6', '\x4', '#', '\n', '\x4', '\r', 
		'\x4', '\xE', '\x4', '$', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '-', '\n', '\x5', '\x3', 
		'\x6', '\x6', '\x6', '\x30', '\n', '\x6', '\r', '\x6', '\xE', '\x6', '\x31', 
		'\x3', '\a', '\x6', '\a', '\x35', '\n', '\a', '\r', '\a', '\xE', '\a', 
		'\x36', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x4', '\x1D', '$', '\x2', '\n', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\x2', '\x3', '\x2', '\x4', '\x4', '\x2', '\v', '\v', '\"', 
		'\"', '\x3', '\x2', '\x32', ';', '\x2', '\x43', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x3', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x15', '\x3', '\x2', '\x2', '\x2', '\a', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\t', ',', '\x3', '\x2', '\x2', '\x2', '\v', '/', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\xF', ':', '\x3', '\x2', '\x2', '\x2', '\x11', '=', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '\x14', '\a', '<', '\x2', '\x2', '\x14', '\x4', '\x3', 
		'\x2', '\x2', '\x2', '\x15', '\x16', '\a', 'N', '\x2', '\x2', '\x16', 
		'\x17', '\a', 'G', '\x2', '\x2', '\x17', '\x18', '\a', 'V', '\x2', '\x2', 
		'\x18', '\x6', '\x3', '\x2', '\x2', '\x2', '\x19', '\x1D', '\x5', '\t', 
		'\x5', '\x2', '\x1A', '\x1C', '\v', '\x2', '\x2', '\x2', '\x1B', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\"', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', ' ', '#', '\x5', '\xF', '\b', '\x2', '!', 
		'#', '\a', '\x2', '\x2', '\x3', '\"', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\"', '!', '\x3', '\x2', '\x2', '\x2', '#', '$', '\x3', '\x2', '\x2', 
		'\x2', '$', '%', '\x3', '\x2', '\x2', '\x2', '$', '\"', '\x3', '\x2', 
		'\x2', '\x2', '%', '&', '\x3', '\x2', '\x2', '\x2', '&', '\'', '\b', '\x4', 
		'\x2', '\x2', '\'', '\b', '\x3', '\x2', '\x2', '\x2', '(', '-', '\a', 
		')', '\x2', '\x2', ')', '*', '\a', 'T', '\x2', '\x2', '*', '+', '\a', 
		'G', '\x2', '\x2', '+', '-', '\a', 'O', '\x2', '\x2', ',', '(', '\x3', 
		'\x2', '\x2', '\x2', ',', ')', '\x3', '\x2', '\x2', '\x2', '-', '\n', 
		'\x3', '\x2', '\x2', '\x2', '.', '\x30', '\x5', '\x11', '\t', '\x2', '/', 
		'.', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '/', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\f', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\x35', '\t', '\x2', '\x2', '\x2', '\x34', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x36', '\x3', '\x2', '\x2', '\x2', '\x36', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x36', '\x37', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\b', '\a', '\x3', 
		'\x2', '\x39', '\xE', '\x3', '\x2', '\x2', '\x2', ':', ';', '\a', '\xF', 
		'\x2', '\x2', ';', '<', '\a', '\f', '\x2', '\x2', '<', '\x10', '\x3', 
		'\x2', '\x2', '\x2', '=', '>', '\t', '\x3', '\x2', '\x2', '>', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x2', '\x1D', '\"', '$', ',', '\x31', 
		'\x36', '\x4', '\b', '\x2', '\x2', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace BASICLanguageParser
