//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Stephen\source\repos\BASICLanguageParser\BASICLanguageParser.Grammar\TestBasic.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BASICLanguageParser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class TestBasicParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, LET=5, EQ=6, ADDITION=7, SUBTRACTION=8, 
		MULTIPLICATION=9, DIVISION=10, VARIABLE_NUMBER=11, VARIABLE_STRING=12, 
		VARIABLE_NUMBER_ARRAY=13, VARIABLE_STRING_ARRAY=14, LETTER=15, STRINGLITERAL=16, 
		DIGIT_SEQUENCE=17, NUMBER=18, COMMENT_BLOCK=19, SKIP_=20, EOL=21;
	public const int
		RULE_prog = 0, RULE_line = 1, RULE_statement = 2, RULE_expression = 3, 
		RULE_characterExpression = 4, RULE_letstmt = 5;
	public static readonly string[] ruleNames = {
		"prog", "line", "statement", "expression", "characterExpression", "letstmt"
	};

	private static readonly string[] _LiteralNames = {
		null, "':'", "'^'", "'('", "')'", "'LET'", "'='", "'+'", "'-'", "'*'", 
		"'/'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "LET", "EQ", "ADDITION", "SUBTRACTION", 
		"MULTIPLICATION", "DIVISION", "VARIABLE_NUMBER", "VARIABLE_STRING", "VARIABLE_NUMBER_ARRAY", 
		"VARIABLE_STRING_ARRAY", "LETTER", "STRINGLITERAL", "DIGIT_SEQUENCE", 
		"NUMBER", "COMMENT_BLOCK", "SKIP_", "EOL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TestBasic.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TestBasicParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public TestBasicParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public TestBasicParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(TestBasicParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestBasicVisitor<TResult> typedVisitor = visitor as ITestBasicVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 13;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 12;
				line();
				}
				}
				State = 15;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==DIGIT_SEQUENCE );
			State = 17;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIGIT_SEQUENCE() { return GetToken(TestBasicParser.DIGIT_SEQUENCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EOL() { return GetToken(TestBasicParser.EOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(TestBasicParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMENT_BLOCK() { return GetTokens(TestBasicParser.COMMENT_BLOCK); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT_BLOCK(int i) {
			return GetToken(TestBasicParser.COMMENT_BLOCK, i);
		}
		public LineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_line; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.EnterLine(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.ExitLine(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestBasicVisitor<TResult> typedVisitor = visitor as ITestBasicVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LineContext line() {
		LineContext _localctx = new LineContext(Context, State);
		EnterRule(_localctx, 2, RULE_line);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 19;
			Match(DIGIT_SEQUENCE);
			State = 22;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LET:
			case VARIABLE_NUMBER:
			case VARIABLE_STRING:
			case VARIABLE_NUMBER_ARRAY:
			case VARIABLE_STRING_ARRAY:
				{
				State = 20;
				statement();
				}
				break;
			case COMMENT_BLOCK:
				{
				State = 21;
				Match(COMMENT_BLOCK);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 31;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 24;
				Match(T__0);
				State = 27;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case LET:
				case VARIABLE_NUMBER:
				case VARIABLE_STRING:
				case VARIABLE_NUMBER_ARRAY:
				case VARIABLE_STRING_ARRAY:
					{
					State = 25;
					statement();
					}
					break;
				case COMMENT_BLOCK:
					{
					State = 26;
					Match(COMMENT_BLOCK);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				}
				State = 33;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 34;
			_la = TokenStream.LA(1);
			if ( !(_la==Eof || _la==EOL) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LetstmtContext letstmt() {
			return GetRuleContext<LetstmtContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestBasicVisitor<TResult> typedVisitor = visitor as ITestBasicVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 4, RULE_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			letstmt();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADDITION() { return GetToken(TestBasicParser.ADDITION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SUBTRACTION() { return GetToken(TestBasicParser.SUBTRACTION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NUMBER_ARRAY() { return GetToken(TestBasicParser.VARIABLE_NUMBER_ARRAY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NUMBER() { return GetToken(TestBasicParser.VARIABLE_NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIGIT_SEQUENCE() { return GetToken(TestBasicParser.DIGIT_SEQUENCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(TestBasicParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULTIPLICATION() { return GetToken(TestBasicParser.MULTIPLICATION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIVISION() { return GetToken(TestBasicParser.DIVISION, 0); }
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestBasicVisitor<TResult> typedVisitor = visitor as ITestBasicVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 6;
		EnterRecursionRule(_localctx, 6, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 49;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ADDITION:
			case SUBTRACTION:
				{
				{
				State = 39;
				_la = TokenStream.LA(1);
				if ( !(_la==ADDITION || _la==SUBTRACTION) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 40;
				expression(0);
				}
				}
				break;
			case VARIABLE_NUMBER_ARRAY:
				{
				State = 41;
				Match(VARIABLE_NUMBER_ARRAY);
				}
				break;
			case VARIABLE_NUMBER:
				{
				State = 42;
				Match(VARIABLE_NUMBER);
				}
				break;
			case DIGIT_SEQUENCE:
				{
				State = 43;
				Match(DIGIT_SEQUENCE);
				}
				break;
			case NUMBER:
				{
				State = 44;
				Match(NUMBER);
				}
				break;
			case T__2:
				{
				State = 45;
				Match(T__2);
				State = 46;
				expression(0);
				State = 47;
				Match(T__3);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 62;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 60;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
					case 1:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 51;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 52;
						_la = TokenStream.LA(1);
						if ( !(_la==MULTIPLICATION || _la==DIVISION) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 53;
						expression(10);
						}
						break;
					case 2:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 54;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 55;
						_la = TokenStream.LA(1);
						if ( !(_la==ADDITION || _la==SUBTRACTION) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 56;
						expression(9);
						}
						break;
					case 3:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 57;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						{
						State = 58;
						Match(T__1);
						State = 59;
						expression(0);
						}
						}
						break;
					}
					} 
				}
				State = 64;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class CharacterExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_STRING_ARRAY() { return GetToken(TestBasicParser.VARIABLE_STRING_ARRAY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_STRING() { return GetToken(TestBasicParser.VARIABLE_STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGLITERAL() { return GetToken(TestBasicParser.STRINGLITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CharacterExpressionContext[] characterExpression() {
			return GetRuleContexts<CharacterExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CharacterExpressionContext characterExpression(int i) {
			return GetRuleContext<CharacterExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADDITION() { return GetToken(TestBasicParser.ADDITION, 0); }
		public CharacterExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_characterExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.EnterCharacterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.ExitCharacterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestBasicVisitor<TResult> typedVisitor = visitor as ITestBasicVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCharacterExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CharacterExpressionContext characterExpression() {
		return characterExpression(0);
	}

	private CharacterExpressionContext characterExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		CharacterExpressionContext _localctx = new CharacterExpressionContext(Context, _parentState);
		CharacterExpressionContext _prevctx = _localctx;
		int _startState = 8;
		EnterRecursionRule(_localctx, 8, RULE_characterExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 69;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VARIABLE_STRING_ARRAY:
				{
				State = 66;
				Match(VARIABLE_STRING_ARRAY);
				}
				break;
			case VARIABLE_STRING:
				{
				State = 67;
				Match(VARIABLE_STRING);
				}
				break;
			case STRINGLITERAL:
				{
				State = 68;
				Match(STRINGLITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 76;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new CharacterExpressionContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_characterExpression);
					State = 71;
					if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
					State = 72;
					Match(ADDITION);
					State = 73;
					characterExpression(5);
					}
					} 
				}
				State = 78;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class LetstmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(TestBasicParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NUMBER_ARRAY() { return GetToken(TestBasicParser.VARIABLE_NUMBER_ARRAY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NUMBER() { return GetToken(TestBasicParser.VARIABLE_NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LET() { return GetToken(TestBasicParser.LET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CharacterExpressionContext characterExpression() {
			return GetRuleContext<CharacterExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_STRING_ARRAY() { return GetToken(TestBasicParser.VARIABLE_STRING_ARRAY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_STRING() { return GetToken(TestBasicParser.VARIABLE_STRING, 0); }
		public LetstmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_letstmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.EnterLetstmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ITestBasicListener typedListener = listener as ITestBasicListener;
			if (typedListener != null) typedListener.ExitLetstmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITestBasicVisitor<TResult> typedVisitor = visitor as ITestBasicVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetstmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LetstmtContext letstmt() {
		LetstmtContext _localctx = new LetstmtContext(Context, State);
		EnterRule(_localctx, 10, RULE_letstmt);
		int _la;
		try {
			State = 91;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 80;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LET) {
					{
					State = 79;
					Match(LET);
					}
				}

				State = 82;
				_la = TokenStream.LA(1);
				if ( !(_la==VARIABLE_NUMBER || _la==VARIABLE_NUMBER_ARRAY) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 83;
				Match(EQ);
				State = 84;
				expression(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LET) {
					{
					State = 85;
					Match(LET);
					}
				}

				State = 88;
				_la = TokenStream.LA(1);
				if ( !(_la==VARIABLE_STRING || _la==VARIABLE_STRING_ARRAY) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 89;
				Match(EQ);
				State = 90;
				characterExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 3: return expression_sempred((ExpressionContext)_localctx, predIndex);
		case 4: return characterExpression_sempred((CharacterExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 9);
		case 1: return Precpred(Context, 8);
		case 2: return Precpred(Context, 7);
		}
		return true;
	}
	private bool characterExpression_sempred(CharacterExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 3: return Precpred(Context, 4);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x17', '`', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x3', '\x2', '\x6', '\x2', 
		'\x10', '\n', '\x2', '\r', '\x2', '\xE', '\x2', '\x11', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', 
		'\x19', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', 
		'\x3', '\x1E', '\n', '\x3', '\a', '\x3', ' ', '\n', '\x3', '\f', '\x3', 
		'\xE', '\x3', '#', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '\x34', '\n', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', '?', '\n', 
		'\x5', '\f', '\x5', '\xE', '\x5', '\x42', '\v', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', 'H', '\n', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'M', '\n', '\x6', '\f', 
		'\x6', '\xE', '\x6', 'P', '\v', '\x6', '\x3', '\a', '\x5', '\a', 'S', 
		'\n', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', 
		'\a', 'Y', '\n', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 
		'^', '\n', '\a', '\x3', '\a', '\x2', '\x4', '\b', '\n', '\b', '\x2', '\x4', 
		'\x6', '\b', '\n', '\f', '\x2', '\a', '\x3', '\x3', '\x17', '\x17', '\x3', 
		'\x2', '\t', '\n', '\x3', '\x2', '\v', '\f', '\x4', '\x2', '\r', '\r', 
		'\xF', '\xF', '\x4', '\x2', '\xE', '\xE', '\x10', '\x10', '\x2', 'k', 
		'\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x4', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '&', '\x3', '\x2', '\x2', '\x2', '\b', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\n', 'G', '\x3', '\x2', '\x2', '\x2', '\f', ']', 
		'\x3', '\x2', '\x2', '\x2', '\xE', '\x10', '\x5', '\x4', '\x3', '\x2', 
		'\xF', '\xE', '\x3', '\x2', '\x2', '\x2', '\x10', '\x11', '\x3', '\x2', 
		'\x2', '\x2', '\x11', '\xF', '\x3', '\x2', '\x2', '\x2', '\x11', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\x12', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x13', '\x14', '\a', '\x2', '\x2', '\x3', '\x14', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x18', '\a', '\x13', '\x2', '\x2', '\x16', '\x19', 
		'\x5', '\x6', '\x4', '\x2', '\x17', '\x19', '\a', '\x15', '\x2', '\x2', 
		'\x18', '\x16', '\x3', '\x2', '\x2', '\x2', '\x18', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '!', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x1D', 
		'\a', '\x3', '\x2', '\x2', '\x1B', '\x1E', '\x5', '\x6', '\x4', '\x2', 
		'\x1C', '\x1E', '\a', '\x15', '\x2', '\x2', '\x1D', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1E', ' ', 
		'\x3', '\x2', '\x2', '\x2', '\x1F', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		' ', '#', '\x3', '\x2', '\x2', '\x2', '!', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '!', '\"', '\x3', '\x2', '\x2', '\x2', '\"', '$', '\x3', '\x2', 
		'\x2', '\x2', '#', '!', '\x3', '\x2', '\x2', '\x2', '$', '%', '\t', '\x2', 
		'\x2', '\x2', '%', '\x5', '\x3', '\x2', '\x2', '\x2', '&', '\'', '\x5', 
		'\f', '\a', '\x2', '\'', '\a', '\x3', '\x2', '\x2', '\x2', '(', ')', '\b', 
		'\x5', '\x1', '\x2', ')', '*', '\t', '\x3', '\x2', '\x2', '*', '\x34', 
		'\x5', '\b', '\x5', '\x2', '+', '\x34', '\a', '\xF', '\x2', '\x2', ',', 
		'\x34', '\a', '\r', '\x2', '\x2', '-', '\x34', '\a', '\x13', '\x2', '\x2', 
		'.', '\x34', '\a', '\x14', '\x2', '\x2', '/', '\x30', '\a', '\x5', '\x2', 
		'\x2', '\x30', '\x31', '\x5', '\b', '\x5', '\x2', '\x31', '\x32', '\a', 
		'\x6', '\x2', '\x2', '\x32', '\x34', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'(', '\x3', '\x2', '\x2', '\x2', '\x33', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x33', ',', '\x3', '\x2', '\x2', '\x2', '\x33', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '.', '\x3', '\x2', '\x2', '\x2', '\x33', '/', '\x3', '\x2', 
		'\x2', '\x2', '\x34', '@', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', 
		'\f', '\v', '\x2', '\x2', '\x36', '\x37', '\t', '\x4', '\x2', '\x2', '\x37', 
		'?', '\x5', '\b', '\x5', '\f', '\x38', '\x39', '\f', '\n', '\x2', '\x2', 
		'\x39', ':', '\t', '\x3', '\x2', '\x2', ':', '?', '\x5', '\b', '\x5', 
		'\v', ';', '<', '\f', '\t', '\x2', '\x2', '<', '=', '\a', '\x4', '\x2', 
		'\x2', '=', '?', '\x5', '\b', '\x5', '\x2', '>', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '>', '\x38', '\x3', '\x2', '\x2', '\x2', '>', ';', '\x3', 
		'\x2', '\x2', '\x2', '?', '\x42', '\x3', '\x2', '\x2', '\x2', '@', '>', 
		'\x3', '\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\b', '\x6', '\x1', '\x2', '\x44', 'H', '\a', '\x10', 
		'\x2', '\x2', '\x45', 'H', '\a', '\xE', '\x2', '\x2', '\x46', 'H', '\a', 
		'\x12', '\x2', '\x2', 'G', '\x43', '\x3', '\x2', '\x2', '\x2', 'G', '\x45', 
		'\x3', '\x2', '\x2', '\x2', 'G', '\x46', '\x3', '\x2', '\x2', '\x2', 'H', 
		'N', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\f', '\x6', '\x2', '\x2', 
		'J', 'K', '\a', '\t', '\x2', '\x2', 'K', 'M', '\x5', '\n', '\x6', '\a', 
		'L', 'I', '\x3', '\x2', '\x2', '\x2', 'M', 'P', '\x3', '\x2', '\x2', '\x2', 
		'N', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x3', '\x2', '\x2', '\x2', 
		'O', '\v', '\x3', '\x2', '\x2', '\x2', 'P', 'N', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'S', '\a', '\a', '\x2', '\x2', 'R', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'U', '\t', '\x5', '\x2', '\x2', 'U', 'V', '\a', '\b', '\x2', 
		'\x2', 'V', '^', '\x5', '\b', '\x5', '\x2', 'W', 'Y', '\a', '\a', '\x2', 
		'\x2', 'X', 'W', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\t', '\x6', '\x2', 
		'\x2', '[', '\\', '\a', '\b', '\x2', '\x2', '\\', '^', '\x5', '\n', '\x6', 
		'\x2', ']', 'R', '\x3', '\x2', '\x2', '\x2', ']', 'X', '\x3', '\x2', '\x2', 
		'\x2', '^', '\r', '\x3', '\x2', '\x2', '\x2', '\xE', '\x11', '\x18', '\x1D', 
		'!', '\x33', '>', '@', 'G', 'N', 'R', 'X', ']',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace BASICLanguageParser
