//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Stephen\source\repos\BASICLanguageParser\BASICLanguageParser.Grammar\TestBasic.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BASICLanguageParser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TestBasicParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface ITestBasicListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TestBasicParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] TestBasicParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestBasicParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] TestBasicParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TestBasicParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] TestBasicParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestBasicParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] TestBasicParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TestBasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] TestBasicParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestBasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] TestBasicParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TestBasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] TestBasicParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestBasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] TestBasicParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TestBasicParser.characterExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacterExpression([NotNull] TestBasicParser.CharacterExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestBasicParser.characterExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacterExpression([NotNull] TestBasicParser.CharacterExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TestBasicParser.letstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetstmt([NotNull] TestBasicParser.LetstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestBasicParser.letstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetstmt([NotNull] TestBasicParser.LetstmtContext context);
}
} // namespace BASICLanguageParser
