//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Stephen\source\repos\BASICLanguageParser\BASICLanguageParser.Grammar\TestBasic.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BASICLanguageParser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class TestBasicLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, LET=5, EQ=6, ADDITION=7, SUBTRACTION=8, 
		MULTIPLICATION=9, DIVISION=10, VARIABLE_NUMBER=11, VARIABLE_STRING=12, 
		VARIABLE_NUMBER_ARRAY=13, VARIABLE_STRING_ARRAY=14, LETTER=15, STRINGLITERAL=16, 
		DIGIT_SEQUENCE=17, NUMBER=18, COMMENT_BLOCK=19, SKIP_=20, EOL=21;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "LET", "EQ", "ADDITION", "SUBTRACTION", 
		"MULTIPLICATION", "DIVISION", "VARIABLE_NUMBER", "VARIABLE_STRING", "VARIABLE_NUMBER_ARRAY", 
		"VARIABLE_STRING_ARRAY", "LETTER", "STRINGLITERAL", "DIGIT_SEQUENCE", 
		"NUMBER", "COMMENT_BLOCK", "SKIP_", "EOL", "COMMENT", "SPACES", "DIGIT"
	};


	public TestBasicLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public TestBasicLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "':'", "'^'", "'('", "')'", "'LET'", "'='", "'+'", "'-'", "'*'", 
		"'/'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "LET", "EQ", "ADDITION", "SUBTRACTION", 
		"MULTIPLICATION", "DIVISION", "VARIABLE_NUMBER", "VARIABLE_STRING", "VARIABLE_NUMBER_ARRAY", 
		"VARIABLE_STRING_ARRAY", "LETTER", "STRINGLITERAL", "DIGIT_SEQUENCE", 
		"NUMBER", "COMMENT_BLOCK", "SKIP_", "EOL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TestBasic.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TestBasicLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x17', '\xC6', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\a', '\f', 'M', '\n', '\f', '\f', '\f', '\xE', '\f', 
		'P', '\v', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', 'Z', 
		'\n', '\xE', '\f', '\xE', '\xE', '\xE', ']', '\v', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\a', '\xF', '\x66', '\n', '\xF', '\f', '\xF', '\xE', '\xF', 
		'i', '\v', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\a', '\x11', 'q', '\n', '\x11', '\f', '\x11', 
		'\xE', '\x11', 't', '\v', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x6', '\x12', 'y', '\n', '\x12', '\r', '\x12', '\xE', '\x12', 
		'z', '\x3', '\x13', '\x6', '\x13', '~', '\n', '\x13', '\r', '\x13', '\xE', 
		'\x13', '\x7F', '\x3', '\x13', '\a', '\x13', '\x83', '\n', '\x13', '\f', 
		'\x13', '\xE', '\x13', '\x86', '\v', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\a', '\x13', '\x8A', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x8D', 
		'\v', '\x13', '\x3', '\x13', '\a', '\x13', '\x90', '\n', '\x13', '\f', 
		'\x13', '\xE', '\x13', '\x93', '\v', '\x13', '\x3', '\x13', '\x5', '\x13', 
		'\x96', '\n', '\x13', '\x3', '\x13', '\a', '\x13', '\x99', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\x9C', '\v', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x5', '\x13', '\xA0', '\n', '\x13', '\x3', '\x13', '\x6', '\x13', 
		'\xA3', '\n', '\x13', '\r', '\x13', '\xE', '\x13', '\xA4', '\x5', '\x13', 
		'\xA7', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x5', '\x16', '\xB0', 
		'\n', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\xB8', '\n', '\x17', '\x3', 
		'\x17', '\a', '\x17', '\xBB', '\n', '\x17', '\f', '\x17', '\xE', '\x17', 
		'\xBE', '\v', '\x17', '\x3', '\x18', '\x6', '\x18', '\xC1', '\n', '\x18', 
		'\r', '\x18', '\xE', '\x18', '\xC2', '\x3', '\x19', '\x3', '\x19', '\x2', 
		'\x2', '\x1A', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', 
		'\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', 
		'\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', 
		'!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', 
		'\x17', '-', '\x2', '/', '\x2', '\x31', '\x2', '\x3', '\x2', '\b', '\x3', 
		'\x2', '\x43', '\\', '\x5', '\x2', '\f', '\f', '\xF', '\xF', '$', '$', 
		'\x4', '\x2', '-', '-', '/', '/', '\x4', '\x2', '\f', '\f', '\xF', '\xF', 
		'\x4', '\x2', '\v', '\v', '\"', '\"', '\x3', '\x2', '\x32', ';', '\x2', 
		'\xD6', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x33', '\x3', '\x2', '\x2', '\x2', '\x5', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\a', '\x37', '\x3', '\x2', '\x2', '\x2', '\t', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\v', ';', '\x3', '\x2', '\x2', '\x2', '\r', 
		'?', '\x3', '\x2', '\x2', '\x2', '\xF', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x43', '\x3', '\x2', '\x2', '\x2', '\x13', '\x45', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'G', '\x3', '\x2', '\x2', '\x2', '\x17', 'I', '\x3', 
		'\x2', '\x2', '\x2', '\x19', 'Q', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'T', '\x3', '\x2', '\x2', '\x2', '\x1D', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', 'l', '\x3', '\x2', '\x2', '\x2', '!', 'n', '\x3', '\x2', '\x2', 
		'\x2', '#', 'x', '\x3', '\x2', '\x2', '\x2', '%', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '\'', '\xA8', '\x3', '\x2', '\x2', '\x2', ')', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '+', '\xAF', '\x3', '\x2', '\x2', '\x2', '-', '\xB7', 
		'\x3', '\x2', '\x2', '\x2', '/', '\xC0', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\a', '<', '\x2', 
		'\x2', '\x34', '\x4', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 
		'`', '\x2', '\x2', '\x36', '\x6', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\a', '*', '\x2', '\x2', '\x38', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x39', ':', '\a', '+', '\x2', '\x2', ':', '\n', '\x3', '\x2', '\x2', 
		'\x2', ';', '<', '\a', 'N', '\x2', '\x2', '<', '=', '\a', 'G', '\x2', 
		'\x2', '=', '>', '\a', 'V', '\x2', '\x2', '>', '\f', '\x3', '\x2', '\x2', 
		'\x2', '?', '@', '\a', '?', '\x2', '\x2', '@', '\xE', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x42', '\a', '-', '\x2', '\x2', '\x42', '\x10', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x44', '\a', '/', '\x2', '\x2', '\x44', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', ',', '\x2', 
		'\x2', '\x46', '\x14', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '\x31', 
		'\x2', '\x2', 'H', '\x16', '\x3', '\x2', '\x2', '\x2', 'I', 'N', '\x5', 
		'\x1F', '\x10', '\x2', 'J', 'M', '\x5', '\x1F', '\x10', '\x2', 'K', 'M', 
		'\x5', '\x31', '\x19', '\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'L', 
		'K', '\x3', '\x2', '\x2', '\x2', 'M', 'P', '\x3', '\x2', '\x2', '\x2', 
		'N', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x3', '\x2', '\x2', '\x2', 
		'O', '\x18', '\x3', '\x2', '\x2', '\x2', 'P', 'N', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'R', '\x5', '\x17', '\f', '\x2', 'R', 'S', '\a', '&', '\x2', 
		'\x2', 'S', '\x1A', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x5', '\x17', 
		'\f', '\x2', 'U', 'V', '\a', '*', '\x2', '\x2', 'V', '[', '\x5', '#', 
		'\x12', '\x2', 'W', 'X', '\a', '.', '\x2', '\x2', 'X', 'Z', '\x5', '#', 
		'\x12', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Z', ']', '\x3', 
		'\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', '[', '\\', 
		'\x3', '\x2', '\x2', '\x2', '\\', '^', '\x3', '\x2', '\x2', '\x2', ']', 
		'[', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', '+', '\x2', '\x2', '_', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\x5', '\x19', '\r', 
		'\x2', '\x61', '\x62', '\a', '*', '\x2', '\x2', '\x62', 'g', '\x5', '#', 
		'\x12', '\x2', '\x63', '\x64', '\a', '.', '\x2', '\x2', '\x64', '\x66', 
		'\x5', '#', '\x12', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', 
		'\x66', 'i', '\x3', '\x2', '\x2', '\x2', 'g', '\x65', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 'h', 'j', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '+', '\x2', 
		'\x2', 'k', '\x1E', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\t', '\x2', 
		'\x2', '\x2', 'm', ' ', '\x3', '\x2', '\x2', '\x2', 'n', 'r', '\a', '$', 
		'\x2', '\x2', 'o', 'q', '\n', '\x3', '\x2', '\x2', 'p', 'o', '\x3', '\x2', 
		'\x2', '\x2', 'q', 't', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', 
		'\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 's', 'u', '\x3', '\x2', 
		'\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '$', 
		'\x2', '\x2', 'v', '\"', '\x3', '\x2', '\x2', '\x2', 'w', 'y', '\x5', 
		'\x31', '\x19', '\x2', 'x', 'w', '\x3', '\x2', '\x2', '\x2', 'y', 'z', 
		'\x3', '\x2', '\x2', '\x2', 'z', 'x', '\x3', '\x2', '\x2', '\x2', 'z', 
		'{', '\x3', '\x2', '\x2', '\x2', '{', '$', '\x3', '\x2', '\x2', '\x2', 
		'|', '~', '\x5', '\x31', '\x19', '\x2', '}', '|', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', '}', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', '\x2', '\x80', '\xA7', 
		'\x3', '\x2', '\x2', '\x2', '\x81', '\x83', '\x5', '\x31', '\x19', '\x2', 
		'\x82', '\x81', '\x3', '\x2', '\x2', '\x2', '\x83', '\x86', '\x3', '\x2', 
		'\x2', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '\x87', '\x3', '\x2', '\x2', '\x2', 
		'\x86', '\x84', '\x3', '\x2', '\x2', '\x2', '\x87', '\x8B', '\a', '\x30', 
		'\x2', '\x2', '\x88', '\x8A', '\x5', '\x31', '\x19', '\x2', '\x89', '\x88', 
		'\x3', '\x2', '\x2', '\x2', '\x8A', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '\x8C', '\xA7', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x90', '\x5', '\x31', '\x19', '\x2', 
		'\x8F', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', 
		'\x3', '\x2', '\x2', '\x2', '\x92', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x94', '\x96', '\a', '\x30', 
		'\x2', '\x2', '\x95', '\x94', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x96', '\x9A', '\x3', '\x2', '\x2', '\x2', 
		'\x97', '\x99', '\x5', '\x31', '\x19', '\x2', '\x98', '\x97', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x98', 
		'\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', '\x2', '\x2', '\x2', 
		'\x9B', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '\x9D', '\x9F', '\a', 'G', '\x2', '\x2', '\x9E', '\xA0', 
		'\t', '\x4', '\x2', '\x2', '\x9F', '\x9E', '\x3', '\x2', '\x2', '\x2', 
		'\x9F', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA2', '\x3', '\x2', 
		'\x2', '\x2', '\xA1', '\xA3', '\x5', '\x31', '\x19', '\x2', '\xA2', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', '\x2', '\x2', '\x2', 
		'\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', 
		'\x2', '\x2', '\xA5', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA6', '}', 
		'\x3', '\x2', '\x2', '\x2', '\xA6', '\x84', '\x3', '\x2', '\x2', '\x2', 
		'\xA6', '\x91', '\x3', '\x2', '\x2', '\x2', '\xA7', '&', '\x3', '\x2', 
		'\x2', '\x2', '\xA8', '\xA9', '\x5', '-', '\x17', '\x2', '\xA9', '(', 
		'\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\x5', '/', '\x18', '\x2', 
		'\xAB', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\b', '\x15', 
		'\x2', '\x2', '\xAD', '*', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB0', 
		'\a', '\xF', '\x2', '\x2', '\xAF', '\xAE', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', 
		'\x2', '\x2', '\xB1', '\xB2', '\a', '\f', '\x2', '\x2', '\xB2', ',', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB8', '\a', ')', '\x2', '\x2', '\xB4', 
		'\xB5', '\a', 'T', '\x2', '\x2', '\xB5', '\xB6', '\a', 'G', '\x2', '\x2', 
		'\xB6', '\xB8', '\a', 'O', '\x2', '\x2', '\xB7', '\xB3', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBC', 
		'\x3', '\x2', '\x2', '\x2', '\xB9', '\xBB', '\n', '\x5', '\x2', '\x2', 
		'\xBA', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBE', '\x3', '\x2', 
		'\x2', '\x2', '\xBC', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', 
		'\x3', '\x2', '\x2', '\x2', '\xBD', '.', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC1', '\t', '\x6', '\x2', 
		'\x2', '\xC0', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\x3', 
		'\x2', '\x2', '\x2', '\xC2', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC2', 
		'\xC3', '\x3', '\x2', '\x2', '\x2', '\xC3', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\xC5', '\t', '\a', '\x2', '\x2', '\xC5', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\x2', 'L', 'N', '[', 'g', 'r', 'z', '\x7F', 
		'\x84', '\x8B', '\x91', '\x95', '\x9A', '\x9F', '\xA4', '\xA6', '\xAF', 
		'\xB7', '\xBC', '\xC2', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace BASICLanguageParser
