//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Stephen\source\repos\BASICLanguageParser\BASICLanguageParser.Grammar\TestBasic.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BASICLanguageParser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TestBasicParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface ITestBasicVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] TestBasicParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] TestBasicParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] TestBasicParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ongotonumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOngotonumstmt([NotNull] TestBasicParser.OngotonumstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ongotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOngotostmt([NotNull] TestBasicParser.OngotostmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ongosubnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOngosubnumstmt([NotNull] TestBasicParser.OngosubnumstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ongosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOngosubstmt([NotNull] TestBasicParser.OngosubstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.gotonumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotonumstmt([NotNull] TestBasicParser.GotonumstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.gotostmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotostmt([NotNull] TestBasicParser.GotostmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.gosubnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGosubnumstmt([NotNull] TestBasicParser.GosubnumstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.gosubstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGosubstmt([NotNull] TestBasicParser.GosubstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.returnstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnstmt([NotNull] TestBasicParser.ReturnstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ifthenelsestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfthenelsestmt([NotNull] TestBasicParser.IfthenelsestmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ifthenelsenumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfthenelsenumstmt([NotNull] TestBasicParser.IfthenelsenumstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ifthenstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfthenstmt([NotNull] TestBasicParser.IfthenstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ifnumelsenumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfnumelsenumstmt([NotNull] TestBasicParser.IfnumelsenumstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ifnumstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfnumstmt([NotNull] TestBasicParser.IfnumstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstmt([NotNull] TestBasicParser.IfstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.letstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetstmt([NotNull] TestBasicParser.LetstmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] TestBasicParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.characterExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacterExpression([NotNull] TestBasicParser.CharacterExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] TestBasicParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] TestBasicParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TestBasicParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOperator([NotNull] TestBasicParser.LogicalOperatorContext context);
}
} // namespace BASICLanguageParser
